//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.UI.srPessoa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaFTR", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.DTO")]
    [System.SerializableAttribute()]
    public partial class PessoaFTR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDTO", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.DTO")]
    [System.SerializableAttribute()]
    public partial class PessoaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CELULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DATANASCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_MAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NUMERO_DE_MEMBROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SEXOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEFONE_FIXOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR {
            get {
                return this.CELULARField;
            }
            set {
                if ((object.ReferenceEquals(this.CELULARField, value) != true)) {
                    this.CELULARField = value;
                    this.RaisePropertyChanged("CELULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATANASC {
            get {
                return this.DATANASCField;
            }
            set {
                if ((this.DATANASCField.Equals(value) != true)) {
                    this.DATANASCField = value;
                    this.RaisePropertyChanged("DATANASC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_MAIL {
            get {
                return this.E_MAILField;
            }
            set {
                if ((object.ReferenceEquals(this.E_MAILField, value) != true)) {
                    this.E_MAILField = value;
                    this.RaisePropertyChanged("E_MAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NUMERO_DE_MEMBRO {
            get {
                return this.NUMERO_DE_MEMBROField;
            }
            set {
                if ((this.NUMERO_DE_MEMBROField.Equals(value) != true)) {
                    this.NUMERO_DE_MEMBROField = value;
                    this.RaisePropertyChanged("NUMERO_DE_MEMBRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO {
            get {
                return this.SEXOField;
            }
            set {
                if ((object.ReferenceEquals(this.SEXOField, value) != true)) {
                    this.SEXOField = value;
                    this.RaisePropertyChanged("SEXO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONE_FIXO {
            get {
                return this.TELEFONE_FIXOField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEFONE_FIXOField, value) != true)) {
                    this.TELEFONE_FIXOField = value;
                    this.RaisePropertyChanged("TELEFONE_FIXO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
    [System.SerializableAttribute()]
    public partial class TokenFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srPessoa.IServicePessoa")]
    public interface IServicePessoa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/ObterLista", ReplyAction="http://tempuri.org/IServicePessoa/ObterListaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srPessoa.TokenFaultContract), Action="http://tempuri.org/IServicePessoa/ObterListaTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        IBL.CPS.UI.srPessoa.PessoaDTO[] ObterLista(IBL.CPS.UI.srPessoa.PessoaFTR Filtro, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/ObterLista", ReplyAction="http://tempuri.org/IServicePessoa/ObterListaResponse")]
        System.Threading.Tasks.Task<IBL.CPS.UI.srPessoa.PessoaDTO[]> ObterListaAsync(IBL.CPS.UI.srPessoa.PessoaFTR Filtro, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Incluir", ReplyAction="http://tempuri.org/IServicePessoa/IncluirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srPessoa.TokenFaultContract), Action="http://tempuri.org/IServicePessoa/IncluirTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Incluir(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Incluir", ReplyAction="http://tempuri.org/IServicePessoa/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Gravar", ReplyAction="http://tempuri.org/IServicePessoa/GravarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srPessoa.TokenFaultContract), Action="http://tempuri.org/IServicePessoa/GravarTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Gravar(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Gravar", ReplyAction="http://tempuri.org/IServicePessoa/GravarResponse")]
        System.Threading.Tasks.Task GravarAsync(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Excluir", ReplyAction="http://tempuri.org/IServicePessoa/ExcluirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srPessoa.TokenFaultContract), Action="http://tempuri.org/IServicePessoa/ExcluirTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Excluir(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Excluir", ReplyAction="http://tempuri.org/IServicePessoa/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Obter", ReplyAction="http://tempuri.org/IServicePessoa/ObterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srPessoa.TokenFaultContract), Action="http://tempuri.org/IServicePessoa/ObterTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        IBL.CPS.UI.srPessoa.PessoaDTO Obter(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePessoa/Obter", ReplyAction="http://tempuri.org/IServicePessoa/ObterResponse")]
        System.Threading.Tasks.Task<IBL.CPS.UI.srPessoa.PessoaDTO> ObterAsync(int id, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePessoaChannel : IBL.CPS.UI.srPessoa.IServicePessoa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePessoaClient : System.ServiceModel.ClientBase<IBL.CPS.UI.srPessoa.IServicePessoa>, IBL.CPS.UI.srPessoa.IServicePessoa {
        
        public ServicePessoaClient() {
        }
        
        public ServicePessoaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePessoaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePessoaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePessoaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IBL.CPS.UI.srPessoa.PessoaDTO[] ObterLista(IBL.CPS.UI.srPessoa.PessoaFTR Filtro, string token) {
            return base.Channel.ObterLista(Filtro, token);
        }
        
        public System.Threading.Tasks.Task<IBL.CPS.UI.srPessoa.PessoaDTO[]> ObterListaAsync(IBL.CPS.UI.srPessoa.PessoaFTR Filtro, string token) {
            return base.Channel.ObterListaAsync(Filtro, token);
        }
        
        public void Incluir(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token) {
            base.Channel.Incluir(dto, token);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token) {
            return base.Channel.IncluirAsync(dto, token);
        }
        
        public void Gravar(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token) {
            base.Channel.Gravar(dto, token);
        }
        
        public System.Threading.Tasks.Task GravarAsync(IBL.CPS.UI.srPessoa.PessoaDTO dto, string token) {
            return base.Channel.GravarAsync(dto, token);
        }
        
        public void Excluir(int id, string token) {
            base.Channel.Excluir(id, token);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(int id, string token) {
            return base.Channel.ExcluirAsync(id, token);
        }
        
        public IBL.CPS.UI.srPessoa.PessoaDTO Obter(int id, string token) {
            return base.Channel.Obter(id, token);
        }
        
        public System.Threading.Tasks.Task<IBL.CPS.UI.srPessoa.PessoaDTO> ObterAsync(int id, string token) {
            return base.Channel.ObterAsync(id, token);
        }
    }
}
