//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBL.CPS.UI.srCasal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CasalFTR", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.DTO")]
    [System.SerializableAttribute()]
    public partial class CasalFTR : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CasalDTO", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.DTO")]
    [System.SerializableAttribute()]
    public partial class CasalDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BAIRROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPLEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENDERECOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUNCAO_ATUALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDESPOSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDMARIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEESPOSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEMARIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMEROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BAIRRO {
            get {
                return this.BAIRROField;
            }
            set {
                if ((object.ReferenceEquals(this.BAIRROField, value) != true)) {
                    this.BAIRROField = value;
                    this.RaisePropertyChanged("BAIRRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIDADE {
            get {
                return this.CIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.CIDADEField, value) != true)) {
                    this.CIDADEField = value;
                    this.RaisePropertyChanged("CIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO {
            get {
                return this.COMPLEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPLEMENTOField, value) != true)) {
                    this.COMPLEMENTOField = value;
                    this.RaisePropertyChanged("COMPLEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENDERECO {
            get {
                return this.ENDERECOField;
            }
            set {
                if ((object.ReferenceEquals(this.ENDERECOField, value) != true)) {
                    this.ENDERECOField = value;
                    this.RaisePropertyChanged("ENDERECO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUNCAO_ATUAL {
            get {
                return this.FUNCAO_ATUALField;
            }
            set {
                if ((this.FUNCAO_ATUALField.Equals(value) != true)) {
                    this.FUNCAO_ATUALField = value;
                    this.RaisePropertyChanged("FUNCAO_ATUAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDESPOSA {
            get {
                return this.IDESPOSAField;
            }
            set {
                if ((this.IDESPOSAField.Equals(value) != true)) {
                    this.IDESPOSAField = value;
                    this.RaisePropertyChanged("IDESPOSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDMARIDO {
            get {
                return this.IDMARIDOField;
            }
            set {
                if ((this.IDMARIDOField.Equals(value) != true)) {
                    this.IDMARIDOField = value;
                    this.RaisePropertyChanged("IDMARIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMEESPOSA {
            get {
                return this.NOMEESPOSAField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEESPOSAField, value) != true)) {
                    this.NOMEESPOSAField = value;
                    this.RaisePropertyChanged("NOMEESPOSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMEMARIDO {
            get {
                return this.NOMEMARIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEMARIDOField, value) != true)) {
                    this.NOMEMARIDOField = value;
                    this.RaisePropertyChanged("NOMEMARIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO {
            get {
                return this.NUMEROField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMEROField, value) != true)) {
                    this.NUMEROField = value;
                    this.RaisePropertyChanged("NUMERO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UF {
            get {
                return this.UFField;
            }
            set {
                if ((object.ReferenceEquals(this.UFField, value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
    [System.SerializableAttribute()]
    public partial class TokenFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srCasal.IServiceCasal")]
    public interface IServiceCasal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/ObterLista", ReplyAction="http://tempuri.org/IServiceCasal/ObterListaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srCasal.TokenFaultContract), Action="http://tempuri.org/IServiceCasal/ObterListaTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        IBL.CPS.UI.srCasal.CasalDTO[] ObterLista(IBL.CPS.UI.srCasal.CasalFTR Filtro, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/ObterLista", ReplyAction="http://tempuri.org/IServiceCasal/ObterListaResponse")]
        System.Threading.Tasks.Task<IBL.CPS.UI.srCasal.CasalDTO[]> ObterListaAsync(IBL.CPS.UI.srCasal.CasalFTR Filtro, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Incluir", ReplyAction="http://tempuri.org/IServiceCasal/IncluirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srCasal.TokenFaultContract), Action="http://tempuri.org/IServiceCasal/IncluirTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Incluir(IBL.CPS.UI.srCasal.CasalDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Incluir", ReplyAction="http://tempuri.org/IServiceCasal/IncluirResponse")]
        System.Threading.Tasks.Task IncluirAsync(IBL.CPS.UI.srCasal.CasalDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Gravar", ReplyAction="http://tempuri.org/IServiceCasal/GravarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srCasal.TokenFaultContract), Action="http://tempuri.org/IServiceCasal/GravarTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Gravar(IBL.CPS.UI.srCasal.CasalDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Gravar", ReplyAction="http://tempuri.org/IServiceCasal/GravarResponse")]
        System.Threading.Tasks.Task GravarAsync(IBL.CPS.UI.srCasal.CasalDTO dto, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Excluir", ReplyAction="http://tempuri.org/IServiceCasal/ExcluirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srCasal.TokenFaultContract), Action="http://tempuri.org/IServiceCasal/ExcluirTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        void Excluir(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Excluir", ReplyAction="http://tempuri.org/IServiceCasal/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Obter", ReplyAction="http://tempuri.org/IServiceCasal/ObterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IBL.CPS.UI.srCasal.TokenFaultContract), Action="http://tempuri.org/IServiceCasal/ObterTokenFaultContractFault", Name="TokenFaultContract", Namespace="http://schemas.datacontract.org/2004/07/IBL.CPS.SERVICOS")]
        IBL.CPS.UI.srCasal.CasalDTO Obter(int id, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCasal/Obter", ReplyAction="http://tempuri.org/IServiceCasal/ObterResponse")]
        System.Threading.Tasks.Task<IBL.CPS.UI.srCasal.CasalDTO> ObterAsync(int id, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCasalChannel : IBL.CPS.UI.srCasal.IServiceCasal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCasalClient : System.ServiceModel.ClientBase<IBL.CPS.UI.srCasal.IServiceCasal>, IBL.CPS.UI.srCasal.IServiceCasal {
        
        public ServiceCasalClient() {
        }
        
        public ServiceCasalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCasalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCasalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCasalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IBL.CPS.UI.srCasal.CasalDTO[] ObterLista(IBL.CPS.UI.srCasal.CasalFTR Filtro, string token) {
            return base.Channel.ObterLista(Filtro, token);
        }
        
        public System.Threading.Tasks.Task<IBL.CPS.UI.srCasal.CasalDTO[]> ObterListaAsync(IBL.CPS.UI.srCasal.CasalFTR Filtro, string token) {
            return base.Channel.ObterListaAsync(Filtro, token);
        }
        
        public void Incluir(IBL.CPS.UI.srCasal.CasalDTO dto, string token) {
            base.Channel.Incluir(dto, token);
        }
        
        public System.Threading.Tasks.Task IncluirAsync(IBL.CPS.UI.srCasal.CasalDTO dto, string token) {
            return base.Channel.IncluirAsync(dto, token);
        }
        
        public void Gravar(IBL.CPS.UI.srCasal.CasalDTO dto, string token) {
            base.Channel.Gravar(dto, token);
        }
        
        public System.Threading.Tasks.Task GravarAsync(IBL.CPS.UI.srCasal.CasalDTO dto, string token) {
            return base.Channel.GravarAsync(dto, token);
        }
        
        public void Excluir(int id, string token) {
            base.Channel.Excluir(id, token);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(int id, string token) {
            return base.Channel.ExcluirAsync(id, token);
        }
        
        public IBL.CPS.UI.srCasal.CasalDTO Obter(int id, string token) {
            return base.Channel.Obter(id, token);
        }
        
        public System.Threading.Tasks.Task<IBL.CPS.UI.srCasal.CasalDTO> ObterAsync(int id, string token) {
            return base.Channel.ObterAsync(id, token);
        }
    }
}
